FROM registry.access.redhat.com/ubi9/nodejs-22:9.7

USER root

RUN dnf install -y java-17-openjdk-headless && dnf clean all

USER 1001

RUN npm i -g @openapitools/openapi-generator-cli && openapi-generator-cli version-manager set 7.18.0

WORKDIR /opt/app-root/src

CMD ["openapi-generator-cli"]